<?php
$escHtml = $this->plugin('escapeHtml');
$escAttr = $this->plugin('escapeHtmlAttr');

$bannerImage              = $this->themeSettingAsset('banner_image');
$bannerHeading            = $this->themeSetting('banner_heading');
$bannerDescription        = $this->themeSetting('banner_description');
$bannerButtonLabel        = $this->themeSetting('banner_button_label');
$bannerButtonLink         = $this->themeSetting('banner_button_link');
$bannerVerticalPosition   = $this->themeSetting('banner_v_position') ?? 'center';
$bannerHorizontalPosition = $this->themeSetting('banner_h_position') ?? 'center';

$class = ['main-banner'];
$hasText = false;
if ($bannerHeading || $bannerDescription || $bannerButtonLink) {
    $class[] = 'has-text';
    $hasText = true;
}

$bannerHeightProperty = $hasText ? 'min-height' : 'height';

$bannerInlineStyles = "{$bannerHeightProperty}: 360px;";
$imageInlineStyles = "object-position: {$bannerHorizontalPosition} {$bannerVerticalPosition};";
?>

<?php if ($bannerImage || $hasText) : ?>
    <div role="banner" class="<?php echo implode(' ', $class); ?>" style="<?php echo $escAttr($bannerInlineStyles); ?>">
        <div class="container main-banner__container">
            <?php if ( $bannerImage ) : ?>
                <div class="main-banner__image-wrapper">
                    <?php echo $this->thumbnail($bannerImage, 'large', ['style' => $imageInlineStyles, 'role' => 'presentation', 'aria-hidden' => 'true']); ?>
                </div>
            <?php endif; ?>

            <div class="main-banner__content">
                <?php if($bannerHeading) : ?>
                    <h2 class="main-banner__heading"><?php echo $escHtml($bannerHeading); ?></h2>
                <?php endif; ?>
                <?php if($bannerDescription) : ?>
                    <p class="main-banner__description"><?php echo nl2br($this->escapeHtml($bannerDescription)); ?></p>
                <?php endif; ?>
                <?php if($bannerButtonLink) : ?>
                    <a class="button" target="_blank" href="<?php echo $this->escapeHtmlAttr($bannerButtonLink); ?>"><?php echo $this->escapeHtml($bannerButtonLabel); ?></a>
                <?php endif; ?>
            </div>
        </div>
    </div>
<?php endif; ?>
