<?php
$hyperlink  = $this->plugin('hyperlink');
$classes    = $classes ?? [];
if (isset($alignmentClass)) {
    $classes[] = $alignmentClass;
    $classes[] = 'file';
}
?>

<div class="<?php echo $this->escapeHtml(implode(' ', $classes)); ?>">
    <?php foreach($attachments as $attachment): ?>
        <?php $item = $attachment->item(); ?>
        <?php if (empty($item)) continue; ?>
        <div class="item resource">
            <?php
            $media = $attachment->media() ?: $item->primaryMedia();
            if ($media) :
                $altText = $media->altText() ?: $media->displayTitle() ?: '';
            ?>
                <?php
                if ($mediaDisplay === 'thumbnail') {
                    switch ($link) {
                        case 'original':
                            $url = $media->originalUrl();
                            break;
                        case 'item':
                            $url = $item->url();
                            break;
                        case 'media':
                            $url = $media->url();
                            break;
                        default:
                            throw new \InvalidArgumentException(sprintf('Invalid link type "%s"', $linkType));
                    }
                    echo $hyperlink->raw($this->thumbnail($media, $thumbnailType, ['alt' => $altText]), $url);
                } else {
                    echo $media->render([
                        'thumbnailType' => $thumbnailType,
                        'thumbnailAttribs' => ['alt' => $altText],
                        'link' => $link,
                    ]);
                }
                ?>
            <?php endif; ?>
            <?php if ($showTitleOption === 'item_title'): ?>
                <h3><?php echo $item->link($item->displayTitle()); ?></h3>
            <?php elseif ($showTitleOption === 'file_name'): ?>
                <h3><?php echo $media->displayTitle(); ?></h3>
            <?php endif; ?>
            <?php $caption = $attachment->caption(); ?>
            <?php if ($caption): ?>
                <div class="caption"><?php echo $caption; ?></div>
            <?php endif; ?>
        </div>
    <?php endforeach; ?>
</div>
