<?php
$resourceMedia = $resource->media();
?>
<?php if ($resourceMedia): ?>
<div class="media-embeds">
    <?php foreach ($resourceMedia as $media): ?>
        <?php $altText = $media->altText() ?: $media->displayTitle() ?: ''; ?>
        <div class="media-embed">
            <?php echo $media->render(['thumbnailAttribs' => ['alt' => $altText]]); ?>
        </div>
    <?php endforeach; ?>
</div>
<?php endif; ?>
